[pytest]

markers = 
    ui: All tests for web browswer
    candymapper: Tests at CandyMapper website
    api: Api calls and validations
    data: Data related tests
    regression: Critical regression tests
    critical: Critical tests
    browser: Browser fixture tests example

python_files = test_*
python_classes = *Test
python_functions = test_*
